source ~/dotfiles/shell/env

# Only load interactive settings when in interactive shells.
[[ $- != *i* ]] && return

source ~/dotfiles/shell/common/load

for file in ~/dotfiles/shell/bash/*.bash; do
  source $file
done

[[ -r ~/.bashrc.local ]] && source ~/.bashrc.local

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
