#!/bin/bash
# vim: set sw=2 ts=2 sts=2 et tw=80 fmr={{{,}}} fdl=0 fdm=marker:
set -euo pipefail
IFS=$'\n\t'

# dotfiles installer for when `make` is not available.

# Prep tasks
mkdir -p ~/.ssh ${XDG_CONFIG_HOME:=$HOME/.config}
touch ~/.ssh/known_hosts
echo "Preparing."

# Initialise submodules
(cd ~/dotfiles && git submodule sync && git submodule update --init)
echo "Submodules done."

# Git config
git config --global color.ui true
git config --global core.editor vim
git config --global core.excludesfile ~/dotfiles/git/globalignore
git config --global diff.mnemonicPrefix true
echo "Git config done."

# Zsh
~/dotfiles/bin/linkup ~/dotfiles/zsh/zshenv ~/.zshenv
~/dotfiles/bin/linkup ~/dotfiles/zsh/zshrc ~/.zshrc
echo "Zsh linked."

# Tmux
~/dotfiles/bin/linkup ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
echo "Tmux linked."

# Ack
~/dotfiles/bin/linkup ~/dotfiles/ack/ackrc ~/.ackrc
echo "Ack linked."

# Vimperator
~/dotfiles/bin/linkup ~/dotfiles/vimperator ~/.vimperator
~/dotfiles/bin/linkup ~/dotfiles/vimperator/vimperatorrc ~/.vimperatorrc
echo "Vimperator linked."

# Vim
~/dotfiles/bin/linkup ~/dotfiles/vim ~/.vim
~/dotfiles/bin/linkup ~/dotfiles/vim/vimrc ~/.vimrc
~/dotfiles/bin/linkup ~/dotfiles/vim $XDG_CONFIG_HOME/nvim
~/dotfiles/bin/linkup ~/dotfiles/vim/vimrc $XDG_CONFIG_HOME/nvim/init.vim
echo "Vim linked."

# vim-plug install process. Starts with plugin list and `nocompatible` flag.
vim -u ~/dotfiles/vim/plugins.vim -N +PlugClean! +PlugUpdate! +quitall!
echo "Vim plugins done."

echo "Install complete!"
