# ~/.tmuxinator/dev.yml
# you can make as many tabs as you wish...

project_name: Tmuxinator
project_root: ~/
tabs:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - 
        - top
