#
# /etc/zshenv is sourced on all invocations of the
# shell, unless the -f option is set.  It should
# contain commands to set the command search path,
# plus other important environment variables.
# .zshenv should not contain commands that produce
# output or assume the shell is attached to a tty.
#

## don't close less when I am done reading
export LESS='-eirMX'
export PAGER=less

## colour ls
export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad

export CVSROOT=:pserver:weiyi@cvs:/usr/cvsroot
export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/git/bin:/usr/local/php/bin:$PATH
export PATH=~/bin:/usr/lib/firefox-3.6:/usr/local/php53/bin:/usr/local/apache2/bin:/usr/local/mysql/bin:/usr/local/bin:/jails/alcatraz/usr/local/www/lithium/current/libraries/lithium/console:$PATH
export JAVA_HOME=/usr/local/java
export ANT_HOME=/Developer/Java/Ant
export CATALINA_HOME=/usr/local/tomcat
export CLASSPATH=/usr/local/cruisecontrol/lib
export FISHEYE_OPTS="-Xms128m -Xmx512m -XX:MaxPermSize=256m"
export FISHEYE_INST=/var/crucible 

# Move Homebrew temp files to ramdisk (build directory)
#export HOMEBREW_TEMP=/Volumes/RamDisk

export DISPLAY=localhost:10.0

# Add /usr/local manpages
if [[ -d /usr/local/share/man ]];then
    MANPATH=$MANPATH:/usr/local/share/man
fi  

if [[ -d /usr/local/man ]];then
    MANPATH=$MANPATH:/usr/local/man
fi  
export MANPATH
