#
# /etc/zshenv is sourced on all invocations of the
# shell, unless the -f option is set.  It should
# contain commands to set the command search path,
# plus other important environment variables.
# .zshenv should not contain commands that produce
# output or assume the shell is attached to a tty.
#

export EDITOR='vim'

## paths
export PATH=$HOME/bin:/usr/local/bin:$PATH # Take user executables before the system's.
export PATH=$HOME/dotfiles/powerline/powerline/scripts:$PATH
export PATH=$HOME/.rvm/bin:$PATH

# Add /usr/local manpages
if [[ -d /usr/local/share/man ]];then
    MANPATH=/usr/local/share/man:$MANPATH
fi
if [[ -d /usr/local/man ]];then
    MANPATH=/usr/local/man:$MANPATH
fi
export MANPATH
