# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/zsh/oh-my-zsh
ZSH_CUSTOM=$HOME/dotfiles/zsh/oh-my-zsh-custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="cinaeco"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git vi-mode ssh-agent)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

## hosts file
alias hosts='sudo vim /etc/hosts'

## history
alias h='history'
## don't show expansions, just execute, e.g. for !! and !$
setopt nohistverify
## don't have the same history across tabs/windows
setopt nosharehistory

## typos
alias scren='screen'

## folder listing/traversal
alias l='ls'
alias ll='ls -hl'
alias la='ls -A'
alias lal="ls -Ahl"
alias cd..='cd ..';
alias ..='cd ..'
alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."

## file manipulation
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias touch='nocorrect touch'
alias ln='nocorrect ln'

## include settings specific to this machine
if [[ -r ~/.zshlocal ]]; then
    source ~/.zshlocal
fi
